/// <reference types="vitest/config" />
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

/**
 * The path the app re-checks event locations through.
 *
 * The event database sends no `access-control-allow-origin`, so a browser
 * cannot read it directly — which is why the schedule ships as a generated
 * file in the first place. A same-origin path that forwards to it lifts that
 * restriction, because the browser is then talking to its own origin.
 *
 * The dev server provides it below. A static host does not, and the app treats
 * its absence as "can't check right now" rather than as an error. To have the
 * check work on a deployed copy, give this path the same forwarding: on
 * Netlify a redirect to `https://gencon.eventdb.us/:splat`, on Cloudflare
 * Pages a function, on nginx a `proxy_pass`.
 */
export const GENCON_PROXY = '/gencon';

// `base: './'` keeps the build portable: it works when served from a domain
// root, from a sub-path (GitHub Pages), or from a native shell's file:// bundle.
export default defineConfig({
  plugins: [react()],
  base: './',
  /*
   * Why the bundle is split, and what splitting it does *not* buy.
   *
   * It was one 710 KB file. Split, it is 191 KB gzipped across eight — which is
   * very slightly *more* to download on a first visit, because each chunk costs
   * a little overhead, and every one of them is `modulepreload`ed anyway. So
   * this is not a first-load optimisation and should not be mistaken for one.
   *
   * What it buys is the second visit and every one after it. The service worker
   * caches by URL, and the filenames carry a content hash, so before this a
   * one-line change to a component invalidated all 710 KB — including Leaflet
   * and React, which had not changed since the project started. Now it
   * invalidates 15 KB and leaves 89 KB of vendor and 62 KB of generated data
   * where they are.
   *
   * The chunks are drawn along what changes together rather than along what is
   * loaded together: the libraries, the traced floor plans, the routing graph,
   * the room table, the stand list. Each is regenerated by its own script, on
   * its own schedule.
   *
   * Genuinely deferring any of them — not fetching the routing graph until
   * somebody asks for directions, or the plans until a building is opened —
   * would take 63 KB off the first load. It is not done, and the number is the
   * reason: `events.json` is 442 KB gzipped and arrives on the same visit, so
   * the saving is 12% of what that visit costs, in exchange for making three
   * synchronous things asynchronous.
   */
  build: {
    rollupOptions: {
      output: {
        manualChunks: (id) => {
          if (id.includes('node_modules/leaflet')) return 'leaflet';
          if (id.includes('node_modules/react')) return 'react';
          if (/src\/data\/(route|pavements|walkable|vertical)\.ts/.test(id)) return 'routing';
          if (/src\/data\/(venue-plan|plan-geometry)\.ts/.test(id)) return 'plans';
          if (/src\/data\/exhibitors\.ts/.test(id)) return 'exhibitors';
          // 839 street addresses, and 80 KB of them. They are what makes an
          // event at a steakhouse walkable, and nothing on the first screen
          // needs one — so they load beside the campus rather than in front
          // of it.
          if (/src\/data\/addresses\.ts/.test(id)) return 'addresses';
          if (/src\/data\/venues\.ts/.test(id)) return 'venues';
          return undefined;
        },
      },
    },
  },
  server: {
    host: true,
    port: 5173,
    proxy: {
      // The same path `functions/gencon/[[path]].js` serves on Cloudflare
      // Pages, so the live check behaves the same in development as deployed.
      [GENCON_PROXY]: {
        target: 'https://www.gencon.com',
        changeOrigin: true,
        rewrite: (path) => path.replace(new RegExp(`^${GENCON_PROXY}`), ''),
      },
    },
  },
  /*
   * Tests run under Vitest, which reads this file — so they get the same
   * plugins, resolution and aliases the app is built with, and there is one
   * build configuration rather than two that can drift apart.
   *
   * jsdom throughout rather than per-file environments: the pure modules don't
   * care which environment they are in, and the components and hooks all need a
   * document. Tests live next to the code they cover.
   */
  test: {
    environment: 'jsdom',
    // The scripts are plain JavaScript and are tested where they live, next to
    // the code, rather than being given hand-written declarations to be
    // importable from `src`.
    include: [
      'src/**/*.test.{ts,tsx}',
      'scripts/**/*.test.mjs',
      'worker/**/*.test.mjs',
      'functions/**/*.test.mjs',
    ],
    // A stubbed geolocation or timer in one file must not leak into the next.
    restoreMocks: true,
    unstubGlobals: true,
  },
});
