

import { fromPack } from './pack-runtime';/**
 * Somewhere to eat downtown, from OpenStreetMap.
 *
 * Generated by scripts/fetch-eateries.mjs — do not edit by hand.
 *
 * Gen Con's own catalogue knows about 43 food trucks on South Street and
 * nothing else, and the convention is in the middle of a city. Everything here
 * carries a name, a cuisine and either opening hours or a website — the other
 * sixty-odd eating places in the box are a name and a dot on a map, and a list
 * a third made of "no idea" is a list nobody scrolls twice.
 *
 * THE HOURS ARE VOLUNTEERS' AND ARE KEPT VERBATIM. `opening_hours` is a real
 * specification and this stores exactly what OSM says; `openingText` in
 * `eateries.ts`'s reader turns the common forms into a sentence and prints the
 * rest as written rather than guessing. `PULLED` is the day they were read,
 * and the app shows it, because a restaurant's hours change and nobody here
 * will know when they do.
 *
 * Source: OpenStreetMap, © OpenStreetMap contributors, ODbL.
 */

export interface Eatery {
  /** OSM's own id, prefixed by element type. Stable enough to key a plan by. */
  id: string;
  name: string;
  /** Restaurant, Café, Fast food, Bar, Pub, Ice cream. */
  kind: string;
  /** OSM's `cuisine`, title-cased and split on its semicolons. */
  cuisine: string[];
  /** `opening_hours`, exactly as written. Absent where nobody has said. */
  hours?: string;
  website?: string;
  /** Only where OSM says yes or only — never where it says limited. */
  diet: string[];
  address?: string;
  lat: number;
  lng: number;
}

/** The day this was read from OpenStreetMap. */
const COMPILED_PULLED = '2026-08-11';

const COMPILED_EATERIES: ReadonlyArray<Eatery> = [
  { id: 'w199161249', name: 'Arby\'s', kind: 'Fast food', cuisine: ['Sandwich'], hours: '10:00-24:00', website: 'https://www.arbys.com/locations/us/in/indianapolis/45-e-south-st/store-7115/', diet: [], address: '45 East South Street', lat: 39.761039, lng: -86.156922 },
  { id: 'n14068844102', name: 'Aroma Indian Cuisine', kind: 'Restaurant', cuisine: ['Indian'], hours: 'Su-Th 11:00-22:00; Fr-Sa 11:00-23:00', website: 'https://www.aromaindy.com', diet: ['Vegetarian'], address: '110 South Pennsylvania Street', lat: 39.765086, lng: -86.156608 },
  { id: 'n3462341164', name: 'Bazbeaux', kind: 'Restaurant', cuisine: ['Pizza'], website: 'https://downtown.bazbeaux.com/', diet: ['Vegetarian'], address: '329 Massachusetts Avenue', lat: 39.771529, lng: -86.153586 },
  { id: 'n7261946385', name: 'Cafe Patachou', kind: 'Restaurant', cuisine: ['Breakfast'], hours: 'Mo-Fr 07:00-15:00; Sa-Su 08:00-15:00', website: 'https://www.cafepatachou.com', diet: [], address: '225 West Washington Street', lat: 39.766932, lng: -86.161991 },
  { id: 'n10838177362', name: 'Caribou Coffee', kind: 'Café', cuisine: ['Coffee Shop'], hours: 'Mo-Th 07:00-18:00; Fr 07:00-15:00', website: 'https://locations.cariboucoffee.com/us/in/indianapolis/420-university-boulevard', diet: [], address: '420 University Boulevard', lat: 39.773703, lng: -86.176407 },
  { id: 'n11975073657', name: 'Chick-fil-A', kind: 'Fast food', cuisine: ['Chicken'], hours: 'Mo-Th 10:00-18:00; Fr 10:00-15:00; Su off', website: 'https://www.chick-fil-a.com/locations/in/indiana-university-purdue-univ-at-indianapolis', diet: [], address: '420 University Boulevard', lat: 39.773631, lng: -86.176446 },
  { id: 'n11975073662', name: 'Chick-fil-A', kind: 'Fast food', cuisine: ['Chicken'], hours: 'Mo-Sa 08:00-21:00; Su off', website: 'https://www.chick-fil-a.com/locations/in/downtown-indy-in-in-line', diet: [], address: '10 East Washington Street', lat: 39.767392, lng: -86.15759 },
  { id: 'n3199022204', name: 'Chipotle', kind: 'Fast food', cuisine: ['Mexican'], hours: 'Mo-Sa 10:30-22:00; Su 10:30-20:00', website: 'https://locations.chipotle.com/in/indianapolis/6-e-washington-st', diet: ['Vegetarian', 'Vegan'], address: '6 East Washington Street', lat: 39.767246, lng: -86.157771 },
  { id: 'n12323959859', name: 'Conner\'s Kitchen + Bar Indianapolis', kind: 'Restaurant', cuisine: ['Grill'], hours: 'Mo-Fr 06:30-10:00, Mo-Fr 11:00-23:00; Sa-Su 07:00-15:00; Sa-Su 16:00-22:00', website: 'https://www.connersindy.com/', diet: [], address: '350 West Maryland Street', lat: 39.765986, lng: -86.164567 },
  { id: 'n14055335001', name: 'Crab 99', kind: 'Restaurant', cuisine: ['Seafood'], hours: 'Mo-Th 14:00-23:00; Fr-Sa 12:00-00:00; Su 12:00-23:00', diet: [], address: '14 East Washington Street', lat: 39.767258, lng: -86.157521 },
  { id: 'n3472080203', name: 'El Toro Bravo', kind: 'Restaurant', cuisine: ['Mexican'], website: 'http://www.acapulco-joes.com/home', diet: ['Vegetarian'], address: '365 North Illinois Street', lat: 39.772573, lng: -86.159445 },
  { id: 'n6479327185', name: 'Five Guys', kind: 'Fast food', cuisine: ['Burger'], hours: '11:00-21:30', website: 'https://restaurants.fiveguys.com/48-e-washington-st', diet: [], address: '48 East Washington Street', lat: 39.767275, lng: -86.15648 },
  { id: 'n12821179674', name: 'Garden Table', kind: 'Restaurant', cuisine: ['American', 'Breakfast'], hours: 'Mo-Su 09:00-15:00', website: 'https://www.thegardentable.com/massave', diet: ['Vegetarian'], address: '342 Massachusetts Avenue', lat: 39.772096, lng: -86.153372 },
  { id: 'n7261911885', name: 'Georgia Street Grind', kind: 'Café', cuisine: ['Coffee Shop'], hours: 'Mo-Fr 07:00-16:00; Sa-Su 08:00-12:00', website: 'https://www.georgiastreetgrind.com', diet: [], address: '25 West Georgia Street', lat: 39.764107, lng: -86.15887 },
  { id: 'n3637475894', name: 'Giorgio\'s Pizza', kind: 'Restaurant', cuisine: ['Pizza'], hours: 'Mo-Th 11:00-21:00; Fr,Sa 11:00-22:00', diet: ['Vegetarian'], lat: 39.768347, lng: -86.156922 },
  { id: 'n11286250677', name: 'Hooters', kind: 'Restaurant', cuisine: ['Burger'], hours: 'Su-Th 11:00-00:00; Fr-Sa 11:00-01:00', diet: [], address: '25 West Georgia Street', lat: 39.76411, lng: -86.158926 },
  { id: 'n3147765431', name: 'India Garden Restaurant', kind: 'Restaurant', cuisine: ['Indian'], hours: 'Mo-Su 11:00-14:30,17:00-22:00', diet: [], address: '209 North Delaware Street', lat: 39.770159, lng: -86.15416 },
  { id: 'n12090615465', name: 'Jack\'s Donuts', kind: 'Fast food', cuisine: ['Donut'], hours: 'Mo-Th 07:00-18:00; Fr-Sa 07:00-20:00; Su 07:00-15:00', website: 'https://www.jacksdonuts.com', diet: [], address: '135 West Market Street', lat: 39.768406, lng: -86.161129 },
  { id: 'n9853805179', name: 'Jimmy John\'s', kind: 'Fast food', cuisine: ['Sandwich'], website: 'https://locations.jimmyjohns.com/in/indianapolis/sandwiches-732.html', diet: [], address: '135 North Pennsylvania Street', lat: 39.769469, lng: -86.155957 },
  { id: 'n9035735531', name: 'Kilwins', kind: 'Ice cream', cuisine: ['Chocolate', 'Ice Cream', 'Popcorn'], hours: 'Th-Su 12:00-22:00; Mo-We 12:00-21:00', diet: [], lat: 39.774476, lng: -86.150168 },
  { id: 'n11619291373', name: 'Lincoln Square Pancake House', kind: 'Restaurant', cuisine: ['American', 'Breakfast', 'Pancake'], hours: '07:00-15:00', website: 'https://www.eatatlincolnsquare.com/market-st', diet: [], address: '150 West Market Street', lat: 39.769146, lng: -86.161413 },
  { id: 'n11418090550', name: 'Loco Fresh Mexican', kind: 'Restaurant', cuisine: ['Mexican'], hours: 'Mo-Su 11:00-21:00', website: 'https://locofreshmexican.com/', diet: [], address: '301 East Market Street', lat: 39.768213, lng: -86.151102 },
  { id: 'n13060589864', name: 'McCormick & Schmick\'s', kind: 'Restaurant', cuisine: ['Seafood', 'Steak'], hours: 'Mo-Th 11:30-21:00; Fr 11:30-22:00; Sa 15:30-22:00; Su 15:30-21:00', diet: [], lat: 39.76876, lng: -86.160235 },
  { id: 'w341317949', name: 'Nesso', kind: 'Restaurant', cuisine: ['Italian'], hours: 'Mo-Sa 17:00-22:00; Su 16:00-21:00', website: 'https://www.nesso-italia.com', diet: [], address: '339 South Delaware Street', lat: 39.7616, lng: -86.154314 },
  { id: 'n11975073658', name: 'Panda Express', kind: 'Fast food', cuisine: ['Chinese'], website: 'https://www.pandaexpress.com/locations/in/indianapolis/2566', diet: [], address: '420 University Boulevard', lat: 39.773998, lng: -86.176055 },
  { id: 'n2941008217', name: 'Panera Bread', kind: 'Fast food', cuisine: ['Sandwich', 'Bakery'], hours: 'Mo-Sa 06:00-19:00; Su 07:00-15:00', website: 'https://locations.panerabread.com/in/indianapolis/110-west-washington-street.html', diet: ['Vegetarian'], address: '110 West Washington Street', lat: 39.767487, lng: -86.1602 },
  { id: 'n12372276438', name: 'Shake Shack', kind: 'Fast food', cuisine: ['Burger'], website: 'https://shakeshack.com/location/downtown-indianapolis-in', diet: [], lat: 39.771047, lng: -86.154596 },
  { id: 'n3637477094', name: 'Small Batch Soups by Soupremacy', kind: 'Restaurant', cuisine: ['Soup'], hours: 'Mo-Fr 07:00-20:00; Sa,Su 09:00-20:00', diet: ['Vegetarian', 'Vegan'], lat: 39.768348, lng: -86.157036 },
  { id: 'n13762052088', name: 'Spoke & Steele', kind: 'Restaurant', cuisine: ['Sandwich', 'Salad', 'Burger', 'Regional', 'American'], website: 'https://www.spokeandsteele.com/home', diet: [], address: '123 South Illinois Street', lat: 39.765059, lng: -86.159778 },
  { id: 'n6479327285', name: 'St. Elmo Steak House', kind: 'Restaurant', cuisine: ['Steak House'], hours: 'Mo-Th 16:00-22:00; Fr 16:00-23:00; Sa 15:00-23:00; Su 16:00-21:00', website: 'https://www.stelmos.com', diet: [], address: '127 South Illinois Street', lat: 39.764818, lng: -86.159716 },
  { id: 'n3414436965', name: 'Starbucks', kind: 'Café', cuisine: ['Coffee Shop'], website: 'https://www.starbucks.com/store-locator/store/13438/mass-ave-430-n-massachusetts-ave-indianapolis-in-462041528-', diet: ['Vegetarian', 'Vegan'], address: '430 Massachusetts Avenue', lat: 39.773237, lng: -86.1519 },
  { id: 'n9900509143', name: 'Starbucks', kind: 'Café', cuisine: ['Coffee Shop'], website: 'https://www.starbucks.com/store-locator/store/10830/hyatt-regency-indianapolis-lob-1-s-capitol-ave-indianapolis-in-462042728-us', diet: [], address: '1 South Capitol Avenue', lat: 39.766557, lng: -86.160906 },
  { id: 'n12227983302', name: 'Starbucks', kind: 'Café', cuisine: ['Coffee Shop'], hours: 'Mo-Th 07:00-17:00; Fr,Sa 07:00-19:00; Su 08:00-14:00', diet: [], lat: 39.773051, lng: -86.166553 },
  { id: 'n12092474308', name: 'Steak \'n Shake', kind: 'Fast food', cuisine: ['Burger'], hours: 'Mo-Th 10:00-00:00; Fr,Sa 10:00-02:00; Su 10:00-00:00', website: 'https://www.steaknshake.com/locations/in-indianapolis-west-maryland/', diet: [], address: '101 West Maryland Street', lat: 39.765501, lng: -86.160231 },
  { id: 'n3170820836', name: 'Subway', kind: 'Fast food', cuisine: ['Sandwich'], hours: 'Mo-Fr 10:00-20:00; Sa 11:00-19:00; Su 12:00-18:00', website: 'https://restaurants.subway.com/united-states/in/indianapolis/421-north-alabama', diet: ['Vegetarian'], address: '421 North Alabama', lat: 39.773417, lng: -86.152241 },
  { id: 'n9900509142', name: 'Subway', kind: 'Fast food', cuisine: ['Sandwich'], hours: 'Mo-Sa 08:00-20:00; Su 09:00-18:00', website: 'https://restaurants.subway.com/united-states/in/indianapolis/111-w-washington-st', diet: [], address: '111 West Washington Street', lat: 39.766132, lng: -86.160782 },
  { id: 'w199161251', name: 'Subway', kind: 'Fast food', cuisine: ['Sandwich'], hours: '09:00-22:00', website: 'https://restaurants.subway.com/united-states/in/indianapolis/31-e-south-st', diet: [], address: '31 East South Street', lat: 39.761249, lng: -86.157476 },
  { id: 'n9855989088', name: 'Sushi Boss', kind: 'Restaurant', cuisine: ['Sushi'], website: 'https://gdsalads.com/', diet: ['Vegetarian', 'Vegan', 'Gluten free'], address: '28 Monument Circle', lat: 39.767838, lng: -86.158254 },
  { id: 'n12536468485', name: 'Sushi Den', kind: 'Restaurant', cuisine: ['Sushi'], website: 'https://sushidenindy.com/', diet: [], address: '233 South Delaware Street', lat: 39.762873, lng: -86.154399 },
  { id: 'n12806342954', name: 'Sweetgreen', kind: 'Fast food', cuisine: ['Salad'], hours: 'Mo-Su 10:30-21:00', diet: [], lat: 39.771061, lng: -86.154855 },
  { id: 'n9931965105', name: 'Ten Hands Social Bar & Eatery', kind: 'Restaurant', cuisine: ['American'], hours: 'Mo-Su 11:00-00:00', website: 'https://www.tenhandsindy.com/', diet: [], address: '241 West Washington Street', lat: 39.766593, lng: -86.163694 },
  { id: 'n10269019985', name: 'The Block Bistro & Grill', kind: 'Restaurant', cuisine: ['American'], hours: 'Mo-Fr 11:00-14:30 open "Lunch", Mo-Th 17:00-21:00 open "Dinner", Fr 17:00-24:00 open "Dinner"; Sa 11:00-24:00; Su 12:00-20:00', website: 'https://www.theblockbistro.com/', diet: [], address: '115 West Market Street', lat: 39.7684, lng: -86.160592 },
  { id: 'n3462341163', name: 'The Eagle', kind: 'Restaurant', cuisine: ['Chicken', 'Sandwich'], hours: 'Mo-Th 11:00-23:00; Fr-Sa 11:00-24:00; Su 11:00-22:00', website: 'https://www.eaglerestaurant.com', diet: ['Vegetarian', 'Vegan'], address: '310 Massachusetts Avenue', lat: 39.771733, lng: -86.153981 },
  { id: 'n9900509144', name: 'The Eagle\'s Nest', kind: 'Restaurant', cuisine: ['American'], hours: 'Mo-Su 17:00-22:00', website: 'https://www.hyatt.com/en-US/hotel/indiana/hyatt-regency-indianapolis/indri/dining', diet: [], address: '1 South Capitol Avenue', lat: 39.766717, lng: -86.1612 },
  { id: 'n11286250676', name: 'The Old Spaghetti Factory', kind: 'Restaurant', cuisine: ['Italian'], hours: 'Mo-Th 11:00-21:30; Fr 11:00-22:30; Sa 12:00-22:30; Su 12:00-21:30', website: 'https://www.osf.com/location/indianapolis-in', diet: [], address: '210 South Meridian Street', lat: 39.764023, lng: -86.158385 },
  { id: 'n3613168293', name: 'The Rathskeller', kind: 'Restaurant', cuisine: ['German'], hours: 'Mo-Th 11:00-21:00; Fr-Sa 11:00-22:00; Su 11:00-21:00', website: 'https://rathskeller.com', diet: ['Vegetarian'], address: '401 East Michigan Street', lat: 39.773786, lng: -86.150017 },
  { id: 'w340008418', name: 'The Social View', kind: 'Restaurant', cuisine: ['American'], hours: 'Mo-Fr 11:00-24:00; Sa-Su 12:00-24:00', website: 'https://www.thesocialviewindy.com/', diet: [], address: '361 Indiana Avenue', lat: 39.772652, lng: -86.162825 },
  { id: 'n11418152969', name: 'Tinker Coffee', kind: 'Café', cuisine: ['Coffee Shop'], hours: 'Mo-Fr 06:00-16:00; Sa-Su 08:00-15:00', website: 'https://www.tinkercoffee.com/', diet: [], address: '380 East Market Street', lat: 39.768513, lng: -86.151014 },
];

/**
 * The pack's copy of this table where one is held, else what was built.
 *
 * Laid over per constant, so a refresh can carry one of these and
 * leave the rest alone, and a key that arrives the wrong shape leaves
 * the compiled value standing. See `fromPack`.
 */
const PACKED = fromPack('eateries', {
  EATERIES: COMPILED_EATERIES,
  PULLED: COMPILED_PULLED,
});

export const EATERIES = PACKED.EATERIES;
export const PULLED = PACKED.PULLED;
