/**
 * Gen Con's own hotel block, and what it charged, generated by
 * `scripts/fetch-block-rates.mjs`.
 *
 * DO NOT EDIT BY HAND — re-run the script.
 *
 * THESE ARE REAL RATES AND THEY ARE OLD. They come from a table an attendee
 * posted on Gen Con's forums in 2019, listing the negotiated block rate for
 * each hotel in 2014, 2015 and 2019. Gen Con publishes block rates nowhere a
 * program can read them, so this is the only record there is.
 *
 * Treat it accordingly: a forum post rather than a Gen Con publication, seven
 * years old, describing the 2019 block. Gen Con moved its housing to Q-rooms
 * for 2026 and the participating list will not be identical to this one.
 * Anything projected from these numbers is an estimate and is drawn as one.
 *
 * Source: https://www.gencon.com/forums/43-travel-housing-and-dining-2019/topics/15787-hotel-costs
 */

export interface Partner {
  /** The id in `lodging.ts` — matched by name, strictly, on generation. */
  placeId: string;
  /** What Gen Con's block called it, which is not always what OSM calls it. */
  blockName: string;
  /** Block rate per night, USD. Null where that year was not in the table. */
  y2014: number | null;
  y2015: number;
  y2019: number;
}

/** The year the newest recorded rates belong to. */
export const BASE_YEAR = 2019;

/** Where these came from, printed on the page beside anything derived. */
export const SOURCE = 'https://www.gencon.com/forums/43-travel-housing-and-dining-2019/topics/15787-hotel-costs';

export const PARTNERS: ReadonlyArray<Partner> = [
  { placeId: 'way340403988', blockName: "Conrad Indianapolis", y2014: 228, y2015: 234, y2019: 259 },
  { placeId: 'way340008421', blockName: "Courtyard by Marriott Capitol", y2014: 179, y2015: 185, y2019: 204 },
  { placeId: 'node4079685108', blockName: "Crowne Plaza at the Union Station", y2014: 194, y2015: 200, y2019: 220 },
  { placeId: 'node5504151850', blockName: "Fairfield Inn & Suites Indianapolis Downtown", y2014: 170, y2015: 175, y2019: 193 },
  { placeId: 'way338986228', blockName: "Hilton Garden Inn Indianapolis Downtown", y2014: 190, y2015: 196, y2019: 216 },
  { placeId: 'way339985727', blockName: "Hilton Indianapolis", y2014: 162, y2015: 167, y2019: 200 },
  { placeId: 'way199297625', blockName: "Holiday Inn Express Hotel & Suites City Center", y2014: 180, y2015: 186, y2019: 205 },
  { placeId: 'way340404001', blockName: "Hyatt Regency Indianapolis", y2014: 206, y2015: 212, y2019: 234 },
  { placeId: 'node5504151848', blockName: "JW Marriott Indianapolis", y2014: 212, y2015: 218, y2019: 246 },
  { placeId: 'node4079685110', blockName: "Le Meridien Indianapolis", y2014: null, y2015: 220, y2019: 245 },
  { placeId: 'way340480884', blockName: "Marriott Indianapolis Downtown", y2014: null, y2015: 212, y2019: 235 },
  { placeId: 'way340480877', blockName: "Omni Severin", y2014: 195, y2015: 201, y2019: 222 },
  { placeId: 'node5504151851', blockName: "SpringHill Suites", y2014: 180, y2015: 185, y2019: 204 },
  { placeId: 'way340480896', blockName: "The Westin", y2014: 195, y2015: 201, y2019: 221 },
];

const BY_PLACE = new Map(PARTNERS.map((one) => [one.placeId, one]));

/** Whether a place was in the 2019 block. */
export const isPartner = (placeId: string): boolean => BY_PLACE.has(placeId);

export const partnerFor = (placeId: string): Partner | null => BY_PLACE.get(placeId) ?? null;
