/**
 * What a room costs, generated by `scripts/fetch-rates.mjs`.
 *
 * DO NOT EDIT BY HAND — re-run the script.
 *
 * One row per place, carrying the **cheapest** quote anybody had and the date of
 * the newest. `sources` is who was asked, because a price is worth as much as
 * its provenance, and `spread` is the gap between the dearest and cheapest
 * quotes for the same place — the honest width of the number.
 *
 * These are indicative nightly rates for a sample night, gathered on free tiers
 * of commercial services. **They are not the Gen Con block rate**, which is
 * behind a badge purchase and a login and cannot be fetched at all.
 */

export interface Rate {
  placeId: string;
  /** The cheapest anybody quoted, per night. */
  nightly: number;
  currency: string;
  /** Who answered. More than one is a stronger number than one. */
  sources: string[];
  /** The newest quote's date, so the page can say how old this is. */
  at: string;
  /** Dearest minus cheapest across sources. Zero when only one answered. */
  spread: number;
}

/** When this file was last written, whether or not anything changed. */
export const REFRESHED = '2026-08-11';

/** The cheapest walkable rate — the cap the drive ring was gathered under. */
export const WALK_FLOOR: number | null = null;

/** Cheapest first. */
export const RATES: ReadonlyArray<Rate> = [

];

const BY_PLACE = new Map(RATES.map((rate) => [rate.placeId, rate]));

export const rateFor = (placeId: string): Rate | null => BY_PLACE.get(placeId) ?? null;
