

import { fromPack } from './pack-runtime';/**
 * What a room costs, generated by `scripts/fetch-rates.mjs`.
 *
 * DO NOT EDIT BY HAND — re-run the script.
 *
 * One row per place, carrying the **cheapest** quote anybody had and the date of
 * the newest. `sources` is who was asked, because a price is worth as much as
 * its provenance, and `spread` is the gap between the dearest and cheapest
 * quotes for the same place — the honest width of the number.
 *
 * These are indicative nightly rates for a sample night, gathered on free tiers
 * of commercial services. **They are not the Gen Con block rate**, which is
 * behind a badge purchase and a login and cannot be fetched at all.
 */

export interface Rate {
  placeId: string;
  /** The cheapest anybody quoted, per night. */
  nightly: number;
  currency: string;
  /** Who answered. More than one is a stronger number than one. */
  sources: string[];
  /** The newest quote's date, so the page can say how old this is. */
  at: string;
  /** Dearest minus cheapest across sources. Zero when only one answered. */
  spread: number;
  /**
   * Where the source said this can be booked, when it said.
   *
   * Not every quote carries one and none gathered before 2026-08 do, so the page
   * treats its absence as ordinary rather than as a fault.
   */
  link?: string | null;
}

/** When this file was last written, whether or not anything changed. */
const COMPILED_REFRESHED = '2026-08-14';

/**
 * The nights these prices are for, and whether they are the convention's own.
 *
 * Hotels open their calendars about a year out, so for most of the year the
 * next Gen Con cannot be booked at all and there is nothing to gather. When
 * that is the case this holds a comparable Wednesday-to-Sunday that *is* on
 * sale, and `isConvention` is false — the page says so rather than letting a
 * quiet week's rate pass for a convention one, which it is not and is cheaper
 * than.
 */
export interface Stay {
  /** Check-in and check-out, ISO. */
  in: string;
  out: string;
  /** Whether these really are the convention's nights, or a stand-in for them. */
  isConvention: boolean;
  conventionYear: number;
  conventionFrom: string;
}

const COMPILED_STAY: Stay = {
  in: '2026-10-14',
  out: '2026-10-18',
  isConvention: false,
  /** The convention these stand in for, when they are standing in. */
  conventionYear: 2027,
  conventionFrom: '2027-08-04',
};

/** The cheapest walkable rate — the cap the drive ring was gathered under. */
const COMPILED_WALK_FLOOR: number | null = 122;

/** Cheapest first. */
const COMPILED_RATES: ReadonlyArray<Rate> = [
  { placeId: 'way1033648891', nightly: 54, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way239624857', nightly: 59, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way219234272', nightly: 60, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way297685504', nightly: 70, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'node12556850850', nightly: 75, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way1225570047', nightly: 75, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way627884885', nightly: 77, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way240398696', nightly: 86, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way195758449', nightly: 89, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way240444147', nightly: 90, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way621313970', nightly: 91, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way1033669563', nightly: 92, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way222676799', nightly: 93, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way702928832', nightly: 93, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way805171306', nightly: 93, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way974343368', nightly: 96, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way242796033', nightly: 98, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way171495008', nightly: 103, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way240442775', nightly: 105, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way240445702', nightly: 105, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way956279347', nightly: 105, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way239624856', nightly: 107, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way972458696', nightly: 107, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way1076486229', nightly: 109, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way956146517', nightly: 111, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way972461709', nightly: 112, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way171495006', nightly: 114, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way702927187', nightly: 114, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way1033674748', nightly: 116, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way679849431', nightly: 116, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way802311024', nightly: 116, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way507057663', nightly: 118, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way994115522', nightly: 120, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'relation4842655', nightly: 122, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way240897267', nightly: 123, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way294890955', nightly: 143, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way596701353', nightly: 143, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'node4079640859', nightly: 145, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way240018523', nightly: 146, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'node4079672858', nightly: 149, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way992299460', nightly: 149, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way171495005', nightly: 150, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way127676083', nightly: 151, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way296789502', nightly: 151, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way195520116', nightly: 153, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way956146515', nightly: 153, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way192523020', nightly: 154, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way195521782', nightly: 169, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way240018513', nightly: 180, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way1225570331', nightly: 182, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way802308281', nightly: 190, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way1025706740', nightly: 192, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way681928379', nightly: 208, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'relation6081914', nightly: 212, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way1123127692', nightly: 246, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
  { placeId: 'way341313486', nightly: 259, currency: 'USD', sources: ['serpapi'], at: '2026-08-14', spread: 0 },
];

/**
 * The pack's copy of this table where one is held, else what was built.
 *
 * Laid over per constant, so a refresh can carry one of these and
 * leave the rest alone, and a key that arrives the wrong shape leaves
 * the compiled value standing. See `fromPack`.
 */
const PACKED = fromPack('rates', {
  RATES: COMPILED_RATES,
  REFRESHED: COMPILED_REFRESHED,
  STAY: COMPILED_STAY,
  WALK_FLOOR: COMPILED_WALK_FLOOR,
});

export const RATES = PACKED.RATES;
export const REFRESHED = PACKED.REFRESHED;
export const STAY = PACKED.STAY;
export const WALK_FLOOR = PACKED.WALK_FLOOR;

const BY_PLACE = new Map(RATES.map((rate) => [rate.placeId, rate]));

export const rateFor = (placeId: string): Rate | null => BY_PLACE.get(placeId) ?? null;

